// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P1_AP1_RomelOrtega.DAL;

#nullable disable

namespace P1_AP1_RomelOrtega.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20251011164017_inicial2")]
    partial class inicial2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("P1_AP1_RomelOrtega.Models.EntradaHuacales", b =>
                {
                    b.Property<int>("IdEntrada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Cantidad")
                        .HasColumnType("REAL");

                    b.Property<int?>("EntradasHuacalesDetalledetalleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.HasKey("IdEntrada");

                    b.HasIndex("EntradasHuacalesDetalledetalleId");

                    b.ToTable("EntradaHuacales");
                });

            modelBuilder.Entity("P1_AP1_RomelOrtega.Models.EntradasHuacalesDetalle", b =>
                {
                    b.Property<int>("detalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdEntrada")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdTipo")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.HasKey("detalleId");

                    b.HasIndex("IdEntrada");

                    b.HasIndex("IdTipo");

                    b.ToTable("EntradasHuacalesDetalle");
                });

            modelBuilder.Entity("P1_AP1_RomelOrtega.Models.TiposHuacales", b =>
                {
                    b.Property<int>("IdTipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Existencia")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdTipo");

                    b.ToTable("TiposHuacales");

                    b.HasData(
                        new
                        {
                            IdTipo = 1,
                            Descripcion = "Huacal Verde, Tamaño Pequeño",
                            Existencia = 10,
                            TipoId = 0
                        },
                        new
                        {
                            IdTipo = 2,
                            Descripcion = "Huacal Verde, Tamaño Mediano",
                            Existencia = 10,
                            TipoId = 0
                        },
                        new
                        {
                            IdTipo = 3,
                            Descripcion = "Huacal Verde, Tamaño Grande",
                            Existencia = 10,
                            TipoId = 0
                        },
                        new
                        {
                            IdTipo = 4,
                            Descripcion = "Huacal Rojo, Tamaño Pequeño",
                            Existencia = 10,
                            TipoId = 0
                        },
                        new
                        {
                            IdTipo = 5,
                            Descripcion = "Huacal Rojo, Tamaño Mediano",
                            Existencia = 10,
                            TipoId = 0
                        },
                        new
                        {
                            IdTipo = 6,
                            Descripcion = "Huacal Rojo, Tamaño Grande",
                            Existencia = 10,
                            TipoId = 0
                        });
                });

            modelBuilder.Entity("P1_AP1_RomelOrtega.Models.EntradaHuacales", b =>
                {
                    b.HasOne("P1_AP1_RomelOrtega.Models.EntradasHuacalesDetalle", null)
                        .WithMany("EntradaHuacalesDetalle")
                        .HasForeignKey("EntradasHuacalesDetalledetalleId");
                });

            modelBuilder.Entity("P1_AP1_RomelOrtega.Models.EntradasHuacalesDetalle", b =>
                {
                    b.HasOne("P1_AP1_RomelOrtega.Models.EntradaHuacales", "EntradaHuacal")
                        .WithMany("EntradasHuacalesDetalles")
                        .HasForeignKey("IdEntrada")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("P1_AP1_RomelOrtega.Models.TiposHuacales", "TipoHuacal")
                        .WithMany("Detalles")
                        .HasForeignKey("IdTipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntradaHuacal");

                    b.Navigation("TipoHuacal");
                });

            modelBuilder.Entity("P1_AP1_RomelOrtega.Models.EntradaHuacales", b =>
                {
                    b.Navigation("EntradasHuacalesDetalles");
                });

            modelBuilder.Entity("P1_AP1_RomelOrtega.Models.EntradasHuacalesDetalle", b =>
                {
                    b.Navigation("EntradaHuacalesDetalle");
                });

            modelBuilder.Entity("P1_AP1_RomelOrtega.Models.TiposHuacales", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
